// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: spade.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CuratorClient is the client API for Curator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CuratorClient interface {
	GetPublicParams(ctx context.Context, in *PublicParamsReq, opts ...grpc.CallOption) (*PublicParamsResp, error)
	UserRequest(ctx context.Context, in *UserReq, opts ...grpc.CallOption) (*UserResp, error)
	Query(ctx context.Context, in *AnalystReq, opts ...grpc.CallOption) (*AnalystResp, error)
}

type curatorClient struct {
	cc grpc.ClientConnInterface
}

func NewCuratorClient(cc grpc.ClientConnInterface) CuratorClient {
	return &curatorClient{cc}
}

func (c *curatorClient) GetPublicParams(ctx context.Context, in *PublicParamsReq, opts ...grpc.CallOption) (*PublicParamsResp, error) {
	out := new(PublicParamsResp)
	err := c.cc.Invoke(ctx, "/spadeproto.Curator/GetPublicParams", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *curatorClient) UserRequest(ctx context.Context, in *UserReq, opts ...grpc.CallOption) (*UserResp, error) {
	out := new(UserResp)
	err := c.cc.Invoke(ctx, "/spadeproto.Curator/UserRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *curatorClient) Query(ctx context.Context, in *AnalystReq, opts ...grpc.CallOption) (*AnalystResp, error) {
	out := new(AnalystResp)
	err := c.cc.Invoke(ctx, "/spadeproto.Curator/Query", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CuratorServer is the server API for Curator service.
// All implementations must embed UnimplementedCuratorServer
// for forward compatibility
type CuratorServer interface {
	GetPublicParams(context.Context, *PublicParamsReq) (*PublicParamsResp, error)
	UserRequest(context.Context, *UserReq) (*UserResp, error)
	Query(context.Context, *AnalystReq) (*AnalystResp, error)
	mustEmbedUnimplementedCuratorServer()
}

// UnimplementedCuratorServer must be embedded to have forward compatible implementations.
type UnimplementedCuratorServer struct {
}

func (UnimplementedCuratorServer) GetPublicParams(context.Context, *PublicParamsReq) (*PublicParamsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPublicParams not implemented")
}
func (UnimplementedCuratorServer) UserRequest(context.Context, *UserReq) (*UserResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserRequest not implemented")
}
func (UnimplementedCuratorServer) Query(context.Context, *AnalystReq) (*AnalystResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Query not implemented")
}
func (UnimplementedCuratorServer) mustEmbedUnimplementedCuratorServer() {}

// UnsafeCuratorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CuratorServer will
// result in compilation errors.
type UnsafeCuratorServer interface {
	mustEmbedUnimplementedCuratorServer()
}

func RegisterCuratorServer(s grpc.ServiceRegistrar, srv CuratorServer) {
	s.RegisterService(&Curator_ServiceDesc, srv)
}

func _Curator_GetPublicParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublicParamsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CuratorServer).GetPublicParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/spadeproto.Curator/GetPublicParams",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CuratorServer).GetPublicParams(ctx, req.(*PublicParamsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Curator_UserRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CuratorServer).UserRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/spadeproto.Curator/UserRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CuratorServer).UserRequest(ctx, req.(*UserReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Curator_Query_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalystReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CuratorServer).Query(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/spadeproto.Curator/Query",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CuratorServer).Query(ctx, req.(*AnalystReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Curator_ServiceDesc is the grpc.ServiceDesc for Curator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Curator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "spadeproto.Curator",
	HandlerType: (*CuratorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPublicParams",
			Handler:    _Curator_GetPublicParams_Handler,
		},
		{
			MethodName: "UserRequest",
			Handler:    _Curator_UserRequest_Handler,
		},
		{
			MethodName: "Query",
			Handler:    _Curator_Query_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "spade.proto",
}
